name: test

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
        
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Install dependencies
        run: pipenv sync --dev

      - name: Build
        run: pipenv run build